# -*- coding: utf-8 -*-
"""init.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jsFne34coSC2TwOlnAVTTuetHvHWXZ4
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=False)
DATASET_DIR = '/content/drive/MyDrive/p_1_image'
!pip install -q tensorflow scikit-image imutils reportlab opencv-python-headless