# -*- coding: utf-8 -*-
"""Test_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkugDI1lO0_5F4TRVX8NxTc6GaeIxjHr
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile your_module.py
# import numpy as np
# from PIL import Image
# 
# def load_img(path, target_size=None):
#     """Loads an image from a given path, resizes it, and returns it as a NumPy array."""
#     img = Image.open(path).convert('RGB')
#     if target_size:
#         img = img.resize(target_size, Image.LANCZOS)
#     return np.array(img)

#Test_data_processing.py
#Prueba que tus funciones de lectura, preprocesamiento y extracción de features funcionen correctamente.

import numpy as np
from skimage.data import camera
from skimage.io import imsave
import matplotlib.pyplot as plt
import os

# Importar la función load_img de your_module.py
from your_module import load_img

# 1. Crear una imagen dummy temporal para probar load_img
# La función camera() de skimage devuelve una imagen en escala de grises, la convertimos a RGB para el ejemplo.
dummy_img_array = camera().astype("uint8")
# Asegurarse de que sea RGB si es en escala de grises
if len(dummy_img_array.shape) == 2:
    dummy_img_array = np.stack([dummy_img_array, dummy_img_array, dummy_img_array], axis=-1)

# Definir una ruta temporal para guardar la imagen
tmp_image_path = "temp_test_image.png"
imsave(tmp_image_path, dummy_img_array)

print(f"Imagen dummy guardada en: {tmp_image_path}")

# 2. Cargar la imagen usando load_img de your_module
target_size = (224, 224)
loaded_image = load_img(tmp_image_path, target_size=target_size)

# 3. Mostrar la imagen cargada
plt.figure(figsize=(6, 6))
plt.imshow(loaded_image)
plt.title(f"Imagen Cargada y Redimensionada a {target_size}")
plt.axis('off') # Ocultar ejes
plt.show()

# Opcional: limpiar el archivo temporal
os.remove(tmp_image_path)
print(f"Archivo temporal {tmp_image_path} eliminado.")

import os
os.environ['PYTHONPATH'] = os.getcwd()
print(f"PYTHONPATH set to: {os.environ['PYTHONPATH']}")

!pytest tests/test_data_processing.py