# -*- coding: utf-8 -*-
"""Test_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkugDI1lO0_5F4TRVX8NxTc6GaeIxjHr
"""



import os

output_dir = "tests"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

file_content = """# tests/test_model.py
import numpy as np
import pytest
import tensorflow as tf
from sklearn.ensemble import RandomForestClassifier

import sys
import os

# --- BEGIN DEBUGGING CODE ---
# Imprime sys.path para ver donde Python busca módulos
print('DEBUG: sys.path at start of test_model.py:', sys.path)
# --- END DEBUGGING CODE ---

# IMPORTA TUS FUNCIONES Y MODELOS
from your_module import build_transfer_model, feature_extractor

# -------------------------------
# Test: modelo CNN se construye
# -------------------------------

def test_cnn_model_builds():
    model = build_transfer_model()
    assert isinstance(model, tf.keras.Model)
    assert model.output_shape[-1] == 2  # 2 clases


# -------------------------------
# Test: CNN produce una prediccion valida
# -------------------------------

def test_cnn_predict_shape():
    model = build_transfer_model()
    dummy = np.zeros((1, 224, 224, 3), dtype="float32")

    pred = model.predict(dummy)
    assert pred.shape == (1, 2)
    assert np.isclose(np.sum(pred), 1.0, atol=1e-4)


# -------------------------------
# Test: embeddings para RF
# -------------------------------

def test_embeddings_extractor():
    dummy = np.zeros((1, 224, 224, 3), dtype="float32")
    emb = feature_extractor.predict(dummy)

    assert emb.ndim == 2     # (batch, features)
    assert emb.shape[0] == 1
    assert emb.shape[1] > 0


# -------------------------------
# Test: RF clasificacion dummy
# -------------------------------

def test_rf_training_dummy():
    X = np.random.rand(20, 128)
    y = np.random.randint(0, 2, 20)

    rf = RandomForestClassifier(n_estimators=10)
    rf.fit(X, y)

    pred = rf.predict([X[0]])
    assert pred[0] in [0, 1]
"""

file_path = os.path.join(output_dir, "test_model.py")
with open(file_path, "w") as f:
    f.write(file_content)

print(f"File '{file_path}' written successfully.")

import sys

# Remove your_module from sys.modules to force a reload
if 'your_module' in sys.modules:
    del sys.modules['your_module']

# Execute pytest again
!pytest tests/test_model.py

with open('your_module.py', 'r') as f:
    print(f.read())

# Commented out IPython magic to ensure Python compatibility.
# %%writefile your_module.py
# import numpy as np
# from PIL import Image
# import tensorflow as tf
# 
# def load_img(path, target_size=None):
#     """Loads an image from a given path, resizes it, and returns it as a NumPy array."""
#     img = Image.open(path).convert('RGB')
#     if target_size:
#         img = img.resize(target_size, Image.LANCZOS)
#     return np.array(img)
# 
# def build_transfer_model():
#     """Placeholder for building a transfer learning model."""
#     # This is a dummy model for testing purposes
#     input_tensor = tf.keras.layers.Input(shape=(224, 224, 3))
#     x = tf.keras.layers.Conv2D(32, (3, 3), activation='relu')(input_tensor)
#     x = tf.keras.layers.GlobalAveragePooling2D()(x)
#     output_tensor = tf.keras.layers.Dense(2, activation='softmax')(x)
#     model = tf.keras.Model(inputs=input_tensor, outputs=output_tensor)
#     return model
# 
# # Placeholder for feature_extractor
# # In a real scenario, this might be a part of the build_transfer_model or a separate model
# feature_extractor = build_transfer_model() # Using the same dummy model for now for testing
#

import os
output_dir = "tests"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
    print(f"Directorio '{output_dir}' creado.")
else:
    print(f"El directorio '{output_dir}' ya existe.")